irqchip/irq-pruss-intc: Fix undeclared ENOTSUPP identifier
Fix the following error by including the proper header file in the
exported irqchip/irq-pruss-intc.h file. Error is thrown when built
for i386-allyesconfig.

include/linux/irqchip/irq-pruss-intc.h:47:10: note: each undeclared identifier is reported only once for each function it appears in
include/linux/irqchip/irq-pruss-intc.h: In function 'pruss_intc_unconfigure':
include/linux/irqchip/irq-pruss-intc.h:53:10: error: 'ENOTSUPP' undeclared (first use in this function)
     return -ENOTSUPP;
             ^~~~~~~~

Reported-by: kbuild test robot <lkp@intel.com>
Fixes: 18a2a382d9dd ("irqchip/irq-pruss-intc: Add helper functions to configure internal mapping")
Signed-off-by: Suman Anna <s-anna@ti.com>
Acked-by: Roger Quadros <rogerq@ti.com>